/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest, NextResponse } from 'next/server';

import { getSupabaseServerAdminClient } from '@kit/supabase/server-admin-client';
import { getSupabaseServerClient } from '@kit/supabase/server-client';

// GET - Get a single changelog entry
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase = getSupabaseServerClient<any>();
  const { data: userData } = await supabase.auth.getUser();
  const user = userData?.user;

  if (!user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const admin = getSupabaseServerAdminClient<any>();

  // Fetch the entry
  const { data: entry, error } = await admin
    .from('changelog_entries')
    .select('*, pull_requests(number, title, github_pr_id)')
    .eq('id', id)
    .maybeSingle();

  if (error) {
    console.error('Error fetching changelog entry:', error);
    return NextResponse.json({ error: 'Failed to fetch entry' }, { status: 500 });
  }

  if (!entry) {
    return NextResponse.json({ error: 'Entry not found' }, { status: 404 });
  }

  // Verify user is member of the org
  const { data: membership } = await admin
    .from('organization_members')
    .select('role')
    .eq('org_id', entry.org_id)
    .eq('user_id', user.id)
    .maybeSingle();

  if (!membership) {
    return NextResponse.json({ error: 'Not a member of this organization' }, { status: 403 });
  }

  return NextResponse.json({ entry });
}

// PATCH - Update a changelog entry
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase = getSupabaseServerClient<any>();
  const { data: userData } = await supabase.auth.getUser();
  const user = userData?.user;

  if (!user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let body: {
    title?: string;
    description?: string;
    category?: 'new_feature' | 'improvement' | 'bug_fix' | 'breaking_change';
    version?: string | null;
    isHidden?: boolean;
  };

  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const admin = getSupabaseServerAdminClient<any>();

  // Fetch the entry to get org_id
  const { data: existing, error: fetchError } = await admin
    .from('changelog_entries')
    .select('org_id, generated_by_llm')
    .eq('id', id)
    .maybeSingle();

  if (fetchError || !existing) {
    return NextResponse.json({ error: 'Entry not found' }, { status: 404 });
  }

  // Verify user is admin of the org
  const { data: membership } = await admin
    .from('organization_members')
    .select('role')
    .eq('org_id', existing.org_id)
    .eq('user_id', user.id)
    .maybeSingle();

  if (!membership || membership.role !== 'admin') {
    return NextResponse.json({ error: 'Only admins can update changelog entries' }, { status: 403 });
  }

  // Build update object
  const updates: Record<string, any> = {
    updated_at: new Date().toISOString(),
  };

  if (body.title !== undefined) updates.title = body.title;
  if (body.description !== undefined) updates.description = body.description;
  if (body.category !== undefined) updates.category = body.category;
  if (body.version !== undefined) updates.version = body.version;
  if (body.isHidden !== undefined) updates.is_hidden = body.isHidden;

  // Mark as admin edited if it was generated by LLM
  if (existing.generated_by_llm && (body.title || body.description)) {
    updates.admin_edited = true;
  }

  // Update entry
  const { data: entry, error } = await admin
    .from('changelog_entries')
    .update(updates)
    .eq('id', id)
    .select()
    .single();

  if (error) {
    console.error('Error updating changelog entry:', error);
    return NextResponse.json({ error: 'Failed to update entry' }, { status: 500 });
  }

  return NextResponse.json({ entry });
}

// DELETE - Delete a changelog entry
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase = getSupabaseServerClient<any>();
  const { data: userData } = await supabase.auth.getUser();
  const user = userData?.user;

  if (!user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const admin = getSupabaseServerAdminClient<any>();

  // Fetch the entry to get org_id
  const { data: existing, error: fetchError } = await admin
    .from('changelog_entries')
    .select('org_id')
    .eq('id', id)
    .maybeSingle();

  if (fetchError || !existing) {
    return NextResponse.json({ error: 'Entry not found' }, { status: 404 });
  }

  // Verify user is admin of the org
  const { data: membership } = await admin
    .from('organization_members')
    .select('role')
    .eq('org_id', existing.org_id)
    .eq('user_id', user.id)
    .maybeSingle();

  if (!membership || membership.role !== 'admin') {
    return NextResponse.json({ error: 'Only admins can delete changelog entries' }, { status: 403 });
  }

  // Delete entry
  const { error } = await admin
    .from('changelog_entries')
    .delete()
    .eq('id', id);

  if (error) {
    console.error('Error deleting changelog entry:', error);
    return NextResponse.json({ error: 'Failed to delete entry' }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}
